# Generated by Django 4.2.6 on 2023-10-12 09:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="drf_cours",
            new_name="drf_courses",
        ),
    ]
